services:
  n8n:
    image: n8nio/n8n:${N8N_VERSION}
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - N8N_PUBLIC_API_BASE_URL=${N8N_PUBLIC_API_BASE_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_SECURE_COOKIE=true
      - GENERIC_TIMEZONE=Europe/Moscow
    env_file:
      - .env
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./local-files:/files
    networks:
      - n8nnet

networks:
  n8nnet:

volumes:
  n8n_storage: